### ISSUE TITLE
Babylon parser issue

### ISSUE THREAD

**Issue by ellisium** [airbnb/babel-plugin-dynamic-import-node#18]
hi 

same this one: 
https://github.com/millermedeiros/esformatter/issues/478
```js
const middleware = import(`./${path.relative(__dirname, dir)}/${item}`) .then(middlewareImport => middlewareImport.default)
```

```sh
at Parser.pp$5.raise (/node_modules/babel-core/node_modules/babylon/lib/index.js:4452:13)
```

**Comment by ljharb** [comment]
That linked issue implies it's an outdated Babylon version. What version are you using?

**Comment by ellisium** [comment]
thank you for your quick reply coz I'm late in my work and it's blocking point for me. I really appreciate your help

`"babel-core": "^6.22.1"`

in babel-core package.json : 
`"babylon": "^6.11.0",`

tested with minium babel-core version specified in babel-plugin-dynamic-import-node package  
`"babel-core": "^6.24.1",`

in babel-core@6.24.1 package.json  (same version is included): 
`"babylon": "^6.11.0",`

I'm surprised because I can use for while your plugin and suddenly I got thir error  since yesterday.

**Comment by ljharb** [comment]
Try `npm update` - I think you need babylon 6.16 or later

**Comment by ellisium** [comment]
updated babel-core and babel-cli to 6.24.1 fix it
thx
