### ISSUE TITLE
Add ability to pre-require modules.

### ISSUE THREAD

**Issue by nickclaw** [airbnb/babel-plugin-dynamic-import-node#19]
For me the main use case for this plugin is to allow bundling of my React app with Webpack while still supporting server side rendering. In a Node environment I actually want the code to be required at startup so the initial SSR isn't delayed while the bundle is evaluated.

If this is something you're interested in supporting I could make a PR, it should be as simple as using a template like `Promise.resolve(require(SOURCE))` when some option is set.

**Comment by ljharb** [comment]
This plugin is aiming to be spec-compliant only - the spec requires that it loads it on the next tick.

If you use `import()`, you are explicitly asking - in all environments - to asynchronously load the file. If you want to load it statically on the server and asynchronously on the client, you'll want a different approach.
