### ISSUE TITLE
when module file use export default ...

### ISSUE THREAD

**Issue by zppro** [airbnb/babel-plugin-dynamic-import-node#25]
my module file use
`export default userSchema;`
when use 
`import('path-to-module').then( module => { let m = module.default; ....})`
so the m is the real module.
it's behavior is not equal to require()
can make import() use like require()?

**Comment by ljharb** [comment]
Nope, you can't.

`import` gives you a ModuleRecord. `require()` pairs with `module.exports` - if you want `require()`, you should use `module.exports = userSchema`, and not `export`/`import`.
