### ISSUE TITLE
Server vs. client

### ISSUE THREAD

**Issue by andywer** [airbnb/babel-plugin-dynamic-import-node#26]
Hi there! This Babel plugin seems particularly useful, but we have got a question about the usage:

Is there anything to take care of when transpiling for both webpack and node as targets or is there a suggested best practice? The readme doesn't mention this use case.

**Comment by ljharb** [comment]
You'd want to use different transforms for each environment. This one for the server, and https://github.com/airbnb/babel-plugin-dynamic-import-webpack for webpack 1 (and webpack 2 can handle `import()` natively).

**Comment by andywer** [comment]
Thanks for the quick response!

Any idea on how to achieve that? Babel environment config doesn't seem like a good choice, since it's not a question of `development` or `production` config, but rather a separate dimension `webpack` vs `node`.

Anyway, might be worth mentioning in the docs 😉

**Comment by ljharb** [comment]
webpack doesn't/shouldn't compile server code; so you'd configure them separately.

Alternatively, you'd want your server and client entry points in different folders; so you could use different `.babelrc` files for each.

PRs to improve the docs are always welcome :-)
