### ISSUE TITLE
1.1.0 breaks React Native

### ISSUE THREAD

**Issue by haggholm** [airbnb/babel-plugin-dynamic-import-node#31]
I don’t know if React Native is an intended target, but hitherto it has worked extremely well. Unfortunately, with 1.1.0, it breaks, as (somehow) we end up with an extra level of functions, with error messages like

> Unknown named module: 'function () {
>		return require(1021	); // 1021 = @client/session
>	}'

IOW it seems that (at least when building with the RN packager) we end up getting a *function* returning the module instead of getting the module itself.

**Comment by ljharb** [comment]
RN should indeed work just fine.

The expected output is https://github.com/airbnb/babel-plugin-dynamic-import-node/blob/master/test/fixtures/basic-import/expected.js (and other things in the fixtures folder).

What's your babel config look like?

cc @vlad-zhukov

**Comment by vlad-zhukov** [comment]
What Reacn Native version do you use? RN supports dynamic imports out of the box: [babel-preset/transforms/transform-dynamic-import.js](https://github.com/facebook/react-native/blob/master/babel-preset/transforms/transform-dynamic-import.js).

It looks like two plugins collide somehow (HOW?! might be a specific of metro-bundler), but anyway you needn't use `babel-plugin-dynamic-import-node` in a modern RN app.
