### ISSUE TITLE
Update dependency?

### ISSUE THREAD

**Issue by mike3run** [airbnb/babel-plugin-dynamic-import-node#39]
[`@babel/plugin-syntax-dynamic-import`](https://github.com/babel/babel/tree/master/packages/babel-plugin-syntax-dynamic-import)

Are there plans to use the package on the newer babel namespace?

**Comment by ljharb** [comment]
That's for babel 7, which isn't fully released yet; when it is, we'll become compatible with it.

**Comment by darkowic** [comment]
@ljharb many people already are using babel-7. Jest is already supporting babel 7. This library is solution for jest issue https://github.com/facebook/jest/issues/2442

Consider supporting new beta babel. Also - is there any plan to move the package to babel scope?

**Comment by ljharb** [comment]
The new babel scope is only for official plugins; so no, it wouldn’t be appropriate to put it under that scope.

Separately, that others have chosen to switch to a beta version doesn’t mean we have to accept the same risks.

**Comment by mike3run** [comment]
@darkowic I posted this with the accepted risks: 

https://www.npmjs.com/package/babel-plugin-dynamic-import-node-babel-7

Its a fork with the updated dependencies and once this package gets official support I'll link to that and issue a deprecation warning.
