### ISSUE TITLE
Code splitting doesn't work with this plugin

### ISSUE THREAD

**Issue by romanlex** [airbnb/babel-plugin-dynamic-import-node#43]
When I add this plugin when code splitting with ```import('./ModuleA')``` doesn't work(((
But If I change import code to ```System.import``` all work perfectly.
You known how I can fix it?

**Comment by ljharb** [comment]
This plugin is for node only; why would you be doing code splitting on server-only code?

**Comment by wenjoy** [comment]
> This plugin is for node only; why would you be doing code splitting on server-only code?

Webpack bundle works in nodejs runtime. I can't agree this issue should be handle like this.

**Comment by ljharb** [comment]
@wenjoy why would you be using webpack for a node server though? what's the use case?

**Comment by wenjoy** [comment]
@ljharb I appreciate your instant reply. Let me clarify. I'm not using `webpack` for a node server. I'm using `webpack` to make a bundle, and babel (as well this babel plugin) as `webpack's` loader to handle some js files. I believe this is the most popular bundle resolution for web application currently.

I hope I have explained clearly. 

Btw, It seems this plugin is a temporary workaround for `@babel/plugin-syntax-dynamic-import`. If I have apply `@babel/plugin-syntax-dynamic-import`, there is no more necessary to use this plugin, right?

Thanks again.

**Comment by ljharb** [comment]
No, that’s not right - this transform requires that syntax plugin.

However, if you’re using webpack 3+, you’d disable the modules transform since webpack handles imports - as such, this plugin would also be disabled for webpack 3+. This plugin is for *node* usage - we have a separate one for webpack 1 and 2.

**Comment by wenjoy** [comment]
Thanks. Make sense.
