### ISSUE TITLE
Which package to use? 

### ISSUE THREAD

**Issue by olstenlarck** [airbnb/babel-plugin-dynamic-import-node#44]
Heya! I'm seeing that there are two packages, pointing to this repo, but one is `v1.2.0` and the another one is `v2.0.0`. So which one to use and which is most recent and okey for future?

- babel-plugin-dynamic-import-node
- babel-plugin-transform-dynamic-import

**Comment by ljharb** [comment]
https://www.npmjs.com/package/babel-plugin-transform-dynamic-import is a fork; I believe for babel 7 support. This one is the official one.

**Comment by olstenlarck** [comment]
Ah thanks. But can't we just add dist-tag here, so to be easier?

**Comment by ljharb** [comment]
Not until babel 7 is actually released.

**Comment by graingert** [comment]
fyi there's another one: https://github.com/mike3run/babel-plugin-dynamic-import-node-babel-7

**Comment by graingert** [comment]
https://npmcompare.com/compare/babel-plugin-dynamic-import,babel-plugin-dynamic-import-node,babel-plugin-dynamic-import-node-babel-7

**Comment by olstenlarck** [comment]
This one is completely working with Babel 7. I don't get what's the point anymore, if there was a point ever.
