### ISSUE TITLE
Error Unknown plugin "dynamic-import-node" specified in "base" at 1,

### ISSUE THREAD

**Issue by IzaGz** [airbnb/babel-plugin-dynamic-import-node#56]
```
node_modules/babel-core/lib/transformation/file/options/option-manager.js:180
          throw new ReferenceError(messages.get("pluginUnknown", plugin, loc, i, dirname));
          ^

ReferenceError: Unknown plugin "dynamic-import-node" specified in "base" at 1, attempted to resolve relative to "/Users/z/project/src/containers"
    at /Users/z/project/src/_server/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/z/project/src/_server/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/z/project/src/_server/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/z/project/src/_server/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (/Users/z/project/src/_server/node_modules/babel-register/lib/node.js:103:45)
    at loader (/Users/z/project/src/_server/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/z/project/src/_server/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)

```

`require('babel-register')({
  plugins: ["transform-decorators-legacy", "dynamic-import-node"],
  presets: ['es2015', 'stage-0', 'react'],
  // ignore: /scss/,
  extensions: [".es6", ".es", ".jsx", ".js"]
});
`
trying to use this plugin cause i got `SyntaxError: Unexpected token import
` on server side rendering
when trying to use webpack dynamic import in my react components

**Comment by ljharb** [comment]
This seems similar to 
https://github.com/airbnb/babel-preset-airbnb/issues/35

Are you babel-transpiling node_modules? This is typically a bad idea.

**Comment by IzaGz** [comment]
@ljharb no i dont do babel to node_modules, i just have ssr, and it required, and worked, but now i have that issue

**Comment by IzaGz** [comment]
@ljharb  yes  of course

**Comment by againksy** [comment]
I have same problem 
on serverSide:
```
    "@babel/core": "^7.0.0-beta.54",
    "@babel/preset-env": "^7.0.0-beta.54",
    "@babel/register": "^7.0.0-beta.54",
    "babel-plugin-dynamic-import-node": "^2.0.0"

```
**********
```
require("@babel/register")({
  "plugins": ["dynamic-import-node"],
  presets: [ '@babel/preset-react', '@babel/preset-env', '@babel/preset-stage-0', ],
});
```

**Comment by againksy** [comment]
Will it be supported for babel >= 7 ?

**Comment by againksy** [comment]
https://github.com/babel/babel/issues/8384 here i have create issue

**Comment by ljharb** [comment]
@againksy when babel 7 is actually released, yes - but not before.

**Comment by IzaGz** [comment]
@ljharb  how can we investigate to make it support?

**Comment by againksy** [comment]
@ljharb hello, seems babel 7 already released, will it be supported?

**Comment by ljharb** [comment]
@againksy nope, it’s still in beta.

**Comment by ljharb** [comment]
Then it’s still not yet released - they just have a *candidate* for release.

When it’s released, we’ll support it. In the meantime, a PR that makes this plugin support both babel 6 and 7 would be helpful, so that such support can be added more quickly once v7 is actually released.

**Comment by ljharb** [comment]
v7 was released 2 days ago; a PR is welcome.

**Comment by ljharb** [comment]
v2.2.0 is released, containing [this commit](https://github.com/airbnb/babel-plugin-dynamic-import-node/commit/8b4d260e31e92c75e68329b1206c04d4397374fa) which allows it to work on both babel 6 and 7.
