### ISSUE TITLE
Repository out of sync with published version in npm?

### ISSUE THREAD

**Issue by ksrb** [airbnb/babel-plugin-dynamic-import-node#58]
Hi I was experimenting with some stuff in create-react-app 2.0 and noticed that this project's code seems to be out of sync with what has been published in npm.

Current `package.json`
https://github.com/airbnb/babel-plugin-dynamic-import-node/blob/3b1982bf26baad3d9b11f78831daf43923fb9264/package.json#L44-L62

`package.json` of `node_modules/babel-plugin-transform-dynamic-import` after `npm i` in new project:
```json
  "devDependencies": {
    "@babel/cli": "7.0.0-beta.34",
    "@babel/core": "7.0.0-beta.34",
    "@babel/plugin-transform-template-literals": "^7.0.0-beta.34",
    "@babel/preset-env": "^7.0.0-beta.34",
    "@babel/preset-es2015": "^7.0.0-beta.34",
    "@babel/register": "7.0.0-beta.34",
    "airbnb-js-shims": "^1.3.0",
    "babel-eslint": "^8.0.3",
    "chai": "^4.1.2",
    "eslint": "^4.11.0",
    "eslint-config-airbnb-base": "^12.1.0",
    "eslint-plugin-import": "^2.8.0",
    "in-publish": "^2.0.0",
    "mocha": "^4.0.1",
    "rimraf": "^2.6.2",
    "safe-publish-latest": "^1.1.1"
  }
```

**Comment by ljharb** [comment]
This is a standard practice; what's published doesn't necessarily reflect what's in the repo.

Things can sit on master for any length of time without being published, and that's ok.

**Comment by ksrb** [comment]
Oh nvm apparently there was a fork that someone published under a very similar name 😅 https://github.com/Timer/babel-plugin-dynamic-import-node/tree/babel-7.

**Comment by ljharb** [comment]
Yes, since babel 7 isn't released yet, we don't yet support it. Once it's actually released, this package will support it.
