### ISSUE TITLE
Update to Babel 7

### ISSUE THREAD

**Issue by wolfy1339** [airbnb/babel-plugin-dynamic-import-node#62]
This is blocking a complete update to Babel 7 in my react app.
It is a dependency of `babel-plugin-react-app`, which uses babel 7

**Comment by ljharb** [comment]
Issues should remain open until a PR is merged.

**Comment by ljharb** [comment]
v2.2.0 is released, containing [this commit](https://github.com/airbnb/babel-plugin-dynamic-import-node/commit/8b4d260e31e92c75e68329b1206c04d4397374fa) which allows it to work on both babel 6 and 7.
