### ISSUE TITLE
Version 2.1.0 not on npm

### ISSUE THREAD

**Issue by wolfy1339** [airbnb/babel-plugin-dynamic-import-node#63]
This repo is at `2.1.0`, while the npm package (babel-plugin-transform-dynamic-import
) is at `2.0.0`. And it uses a beta version of Babel 7, while this repo is still at Babel 6.
Please update both the repo and the npm package please

**Comment by ljharb** [comment]
v2.1 is definitely on npm: https://unpkg.com/babel-plugin-dynamic-import-node@2.1.0/

**Comment by wolfy1339** [comment]
You didn't read my message properly, i was talking about `babel-plugin-transform-dynamic-import`, not the same name, but it points to this repo and is used in `create-react-app`. So which one is the correct name?

**Comment by ljharb** [comment]
No idea - I didn't publish it, and it seems like someone just stole the code and republished it under a different name.

cc @gaearon; do you know why CRA is using `babel-plugin-transform-dynamic-import` which uses this repo's code but without the knowledge of its maintainers?

**Comment by wolfy1339** [comment]
Just for reference in CRA: https://github.com/facebook/create-react-app/blob/next/packages/babel-preset-react-app/package.json#L33

**Comment by wolfy1339** [comment]
The package seems like someone forked it and made it work for babel 7.0.0-beta.34, https://unpkg.com/babel-plugin-transform-dynamic-import@2.0.0/

So this could just very well be a misunderstanding, since they haven'y updated the meta info in `package.json`

**Comment by wolfy1339** [comment]
facebook/create-react-app#4984 fixes this.
