### ISSUE TITLE
 Bring the file suffix name, the compilation result cannot be executed

### ISSUE THREAD

**Issue by nokisnojok** [airbnb/babel-plugin-dynamic-import-node#72]
source code
`
import ('./index.jsx')
`
build result:
`
   Promise.resolve().then(() => _interopRequireWildcard(require('./index.jsx')));
`

It doesn`t work

**Comment by ljharb** [comment]
what doesn’t work about it?

**Comment by ljharb** [comment]
Note that the jsx extension can’t be required in node, and it’s a best practice to omit extensions - try just `import('./')`
