### ISSUE TITLE
missing support for query params and fragments

### ISSUE THREAD

**Issue by dnalborczyk** [airbnb/babel-plugin-dynamic-import-node#74]
> Matches the proposed spec.

are query params and fragments part of the spec?

repro:

```js
await import('./index.js#test')
// throws: Cannot find module './index.js#test'
```

```js
await import('./index.js?test=test')
// throws: Cannot find module './index.js?test=test'
```

in addition, this makes it impossible to force reimporting a module and get a fresh module record, e.g. for loading modules in tests.

**Comment by ljharb** [comment]
That path is not a URL - it's a specifier, by spec. The spec requires it be treated as an opaque identifier by everything except the host itself. So, anything you `import()` that won't work as a require in node, is something you'd need a different transform for - or better, import maps in the browser (ie, your code should match node, the browser should need a build process).

**Comment by dnalborczyk** [comment]
thanks @ljharb ! basically you are stating, my "host" is `node.js` with cjs `require`. whatever this provides, goes. Makes sense.

I was mainly just trying to invalidate dynamically imported modules for some tests, meaning I needed to have a "fresh" module to test - with no existing state. but now thinking about it, even if the plugin could handle the invalidation (aka load another module instance) case, there would be no import.meta object either, and therefore no url to read the additional parameters from. so, somewhat pointless to provide a query or fragment then.

**Comment by ljharb** [comment]
You can do that with `delete require.cache[require.resolve(specifier)]`.
