### ISSUE TITLE
No description in github releases

### ISSUE THREAD

**Issue by Alendorff** [airbnb/babel-plugin-dynamic-import-node#76]
I just wanted to check what's new happened since current version I have (1.2.0), but I see nothing in [releases](https://github.com/airbnb/babel-plugin-dynamic-import-node/releases).

😟

**Comment by ljharb** [comment]
https://github.com/airbnb/babel-plugin-dynamic-import-node/blob/master/CHANGELOG.md (a repo level changelog file is much more commonly used than github releases)
