### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by wmm387** [airbnb/babel-plugin-dynamic-import-node#88]
### in vue-router

      {
        path: '/',
        name: 'home',
        component: () => import('@/views/home/index'),
        meta: {
          title: 'Home'
        }
      }

error: Critical dependency: the request of a dependency is an expression;
webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:17 [vue-router] Failed to resolve async component default: Error: Cannot find module '@/views/home/index'

Rolling back and locking into 2.3.0 resolves the issue.

**Comment by haiweilian** [comment]
I also have this problem.

**Comment by imzyxwvu** [comment]
Me too. Downgrading fixes this.

**Comment by CiklopLT** [comment]
Same here, should be downgraded to 2.3.0

**Comment by KnisterPeter** [comment]
The created output here is something like this:
```js
Promise.resolve('prefix-${var}').then(s => require(s))
```
If this is check by webpack, it results in unmatched dynamic imports.
Webpack could understand `require('prefix-${var}')` but not `require(s)`

The fix for #84 need to be reverted and fixed in another way.

**Comment by ljharb** [comment]
cc @nicolo-ribaudo we may have to revert to the original, but still *evaluate* the result twice so as to evaluate it sync?

**Comment by ljharb** [comment]
@KnisterPeter this plugin is for *node*, not for webpack - we have https://github.com/airbnb/babel-plugin-dynamic-import-webpack for webpack 1 and 2, and webpack 3+ understands this syntax natively.

**Comment by KnisterPeter** [comment]
@ljharb Thanks for the hint

**Comment by nicolo-ribaudo** [comment]
> cc @nicolo-ribaudo we may have to revert to the original, but still evaluate the result twice so as to evaluate it sync?

Evaluating twice is worse than evaluating asynchronously. Also, it would bring back the bug that originally led to that PR (`yield` or `await` inside import arguments).

If the dynamic import argument is a single `StringLiteral`, we could transpile it to
```js
Promise.resolve().then(s => require("./module"))
```
in more complex cases where it would be observable, I think that it is better to do the correct thing rather than trying to adapt the output to webpack, which doesn't need this plugin in the first place.
