### ISSUE TITLE
Variables in dynamic imports broken after 2.3.0

### ISSUE THREAD

**Issue by richarddd** [airbnb/babel-plugin-dynamic-import-node#90]
Node can no longer find my dynamic imports from version 2.3.3.

I compared the generated bundles and found this diff:
Before:
```javascript
await Promise.resolve().then(() => __webpack_require__("./src/api sync recursive ^\\.\\/.*$")(`./${functionName}`));
```

After:
```javascript
await Promise.resolve(`api/${functionName}`).then(s => __webpack_require__("./src sync recursive")(s));
```

This is the error produced:
```
Error: Cannot find module 'api/pdf'
    at webpackEmptyContext (/Users/richard/Projects/riktiga-vykort/.webpack/service/src/webpack:/src sync:2:1)
```

This is my source:
```javascript
  const functionName = process.env.FUNCTION_NAME

  await import(
    `api/${functionName}`
  )
```

**Comment by nicolo-ribaudo** [comment]
Question: why do you use this plugin with webpack? Webpack natively supports dynamic import.

Also, we tried thinking about a solution that respects the dynamic import semantics (i.e. the import argument is evaluated synchronously) and works with webpack (even if this plugin shouldn't be used with webpack), but we couldn't find it.

i.e.
```js
let i = 0;
import(`./file-${i++}.js`);
console.log(i);
```
it should log `1` and import `file-0.js`.

**Comment by richarddd** [comment]
> Question: why do you use this plugin with webpack? Webpack natively supports dynamic import.
> 
> Also, we tried thinking about a solution that respects the dynamic import semantics (i.e. the import argument is evaluated synchronously) and works with webpack (even if this plugin shouldn't be used with webpack), but we couldn't find it.
> 
> i.e.
> 
> ```js
> let i = 0;
> import(`./file-${i++}.js`);
> console.log(i);
> ```
> 
> it should log `1` and import `file-0.js`.

Doh! I can't figure out a reason why. Removed it and now we dont have problem. Thanls :)
