### ISSUE TITLE
Specifier should not be resolved

### ISSUE THREAD

**Issue by Josh-Cena** [airbnb/babel-plugin-dynamic-import-node#93]
While working on https://github.com/microsoft/TypeScript/pull/49663, Ron Buckton pointed out a pitfall in my initial implementation, which was largely inspired by this plugin. Example:

```js
const a = import(Promise.resolve("foo"));
```

This should be importing `[object Object]`, instead of `foo`.

Alternative solution is proposed in https://github.com/microsoft/TypeScript/pull/49663#discussion_r908929763

**Comment by nicolo-ribaudo** [comment]
This package passes a string to `Promise.resolve`, so it doesn't suffer from that problem. Remember that the import specifier should be stringified synchronously.

**Comment by Josh-Cena** [comment]
Oh—I see. Forgot to try it first. Thanks for pointing out!
